version: '3.8'

services:
  # 1. ฐานข้อมูล PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: pos_postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: user # ต้องตรงกับ app.module.ts
      POSTGRES_PASSWORD: password # ต้องตรงกับ app.module.ts
      POSTGRES_DB: pos_db # ชื่อ Database
    volumes:
      - postgres_data_v2:/var/lib/postgresql/data
    restart: always

  # 2. Redis (เผื่อใช้ Caching หรือ Session ในอนาคต)
  redis:
    image: redis:alpine
    container_name: pos_redis
    ports:
      - "6379:6379"
    restart: always

  # 3. PgAdmin (หน้าเว็บสำหรับจัดการ Database - Optional)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pos_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data_v2:
